# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2228e2c9dfad5a2e5a5031b760169d632f012b4ee9f369f4aec457c06ee6d1ad0428a65dea72fd40c3bcbefc5a0de0488cb69ac96551a87e4804f9f13b6c9d

test:
  secret_key_base: 434e4a575b088cacf9dc67ff7caa647c0a4c2117be5f32991ef0d811213069d8b76254c6459673ecb48de8255e5fc8d96f567e499dc3a91e16903bc2b3c6d866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
